const AI_PROVIDERS = {
  OPENAI: "openai",
  GEMINI: "gemini",
  OLLAMA: "ollama",
  AZURE_FOUNDRY: "azure-foundry",
  DEFAULT: "AI",
};

const PROCESSING_MODES = {
  ANALYTICS: "analytics",
  UI_IMPLEMENTATION: "ui_implementation",
  QUICK_ANSWER: "quick_answer",
};

const IPC_CHANNELS = {
  UPDATE_INSTRUCTION: "update-instruction",
  HIDE_INSTRUCTION: "hide-instruction",
  UPDATE_VISIBILITY: "update-visibility",
  TOGGLE_VISIBILITY: "toggle-visibility",
  NOTIFICATION: "notification",
  LOADING: "loading",
  ANALYSIS_RESULT: "analysis-result",
  STREAM_START: "stream-start",
  STREAM_CHUNK: "stream-chunk",
  STREAM_UPDATE: "stream-update",
  STREAM_END: "stream-end",
  CLEAR_RESULT: "clear-result",
  MODEL_CHANGED: "model-changed",
  SCREEN_SHARING_DETECTED: "screen-sharing-detected",
  GET_CURRENT_SETTINGS: "get-current-settings",
  SHOW_CONTEXT_MENU: "show-context-menu",
  TOGGLE_DEVTOOLS: "toggle-devtools",
  UPDATE_MODEL_SETTINGS: "update-model-settings",
  SCREENSHOT_READY_FOR_PROCESSING: "screenshot-ready-for-processing",
  GET_OLLAMA_MODELS: "get-ollama-models",
  DEV_RELOAD: "dev-reload",
  SCROLL_CONTENT: "scroll-content",
  RESIZE_WINDOW: "resize-window",
  MOVE_WINDOW: "move-window",
  QUIT_APP: "quit-app",
  SAVE_API_KEY: "save-api-key",
  GET_API_KEY: "get-api-key",
  GET_ALL_API_KEYS: "get-all-api-keys",
  INITIALIZE_AI_CLIENT: "initialize-ai-client",
  SEND_CHAT_MESSAGE: "send-chat-message",
  CHAT_MESSAGE_RESPONSE: "chat-message-response",
  CHAT_MESSAGE_STREAM_START: "chat-message-stream-start",
  CHAT_MESSAGE_STREAM_CHUNK: "chat-message-stream-chunk",
  CHAT_MESSAGE_STREAM_END: "chat-message-stream-end",
  TOGGLE_SPLIT_VIEW: "toggle-split-view",
  UPDATE_SYSTEM_PROMPT: "update-system-prompt",
  GET_SYSTEM_PROMPT: "get-system-prompt",
  SHOW_HOTKEYS_INFO: "show-hotkeys-info",
  CLEAR_CONVERSATION: "clear-conversation",
  GET_CONVERSATION: "get-conversation",
  UPDATE_AVAILABLE: "update-available",
  UPDATE_ACTION: "update-action",
  SHOW_UPDATE_DIALOG: "show-update-dialog",
  SHOW_UPDATE_TOOLBAR_BUTTON: "show-update-toolbar-button",
  UI_IMPLEMENTATION_MODE: "ui-implementation-mode",
  PROCESS_UI_SCREENSHOT: "process-ui-screenshot",
  DIRECT_ANSWER_MODE: "direct-answer-mode",
  PROCESS_DIRECT_ANSWER: "process-direct-answer",
  CANCEL_AI_REQUEST: "cancel-ai-request",
  MODE_CHANGED: "mode-changed",
  GET_CURRENT_MODE: "get-current-mode",
  // Voice (Ctrl+L) — system audio → Web Speech API → Gemini answer with furigana
  VOICE_TOGGLE: "voice-toggle",
  VOICE_STATE_CHANGED: "voice-state-changed",
  VOICE_INTERIM_TRANSCRIPT: "voice-interim-transcript",
  VOICE_FINAL_TRANSCRIPT: "voice-final-transcript",
  VOICE_ERROR: "voice-error",
  VOICE_GET_AUDIO_SOURCE: "voice-get-audio-source",
  VOICE_SUBMIT_AUDIO: "voice-submit-audio",
  VOICE_LIVE_TRANSCRIPT: "voice-live-transcript",
  VOICE_QUESTION_ANSWER_START: "voice-question-answer-start",
  VOICE_QUESTION_ANSWER_CHUNK: "voice-question-answer-chunk",
  VOICE_QUESTION_ANSWER_END: "voice-question-answer-end",
};

module.exports = {
  AI_PROVIDERS,
  PROCESSING_MODES,
  IPC_CHANNELS,
};
